### ISSUE TITLE
ValueError using markets structure/region id

### ISSUE THREAD

**Issue by tobwin** [Kyria/EsiPy#12]
I get an error calling the following:

`esi_app.op['get_markets_structures_structure_id'](structure_id=12345)`
> ValueError: Can't resolve type from:(number, int32)

The very same happens when I use the code from the documentation:

`market_order_operation = app.op['get_markets_region_id_orders'](
    region_id=1002,
    type_id=34,
    order_type='all')`

**Comment by Kyria** [comment]
Looks like it comes from ESI recent changes, but not well handled by pyswagger... 
Gonna open a ticket there for this issue...

**Comment by tobwin** [comment]
Thanks a lot!

**Comment by Kyria** [comment]
There is a temporary solution, until this is fixed pyswagger side (or mine, if he doesn't want to fix it). 

Instead of using `App.create()` you'll have to do this:

```python
from esipy import App

# register new primitives builder
from pyswagger.primitives import Primitive
from pyswagger.primitives._int import create_int, validate_int
factory = Primitive()
factory.register('number', 'int64', create_int, validate_int)
factory.register('number', 'int32', create_int, validate_int)

# load the esi swagger
app = App.load('https://esi.tech.ccp.is/latest/swagger.json?datasource=tranquility', prim=factory)
app.prepare(True)

app.op['get_markets_structures_structure_id'](structure_id=12345)
(<pyswagger.io.Request object at 0x700383b36c10>, <pyswagger.io.Response object at 0x700382d9fc50>)
``` 

Keep in mind this is only a temporary solution (so it doesn't block your app/dev), at the end, you'll just have to use `App.create()` again :)

**Comment by Kyria** [comment]
@tobwin if you update your esipy dependencies (to have pyswagger 0.8.31) it should resolve your issue. I can't test it myself right now, but i'll close this issue as soon as you confirm this / i'll test it.
