### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by EricE** [Kyria/EsiPy#16]
A very minor issue, unfortunately I don't know how to use github to send you the fix, someday...  In "Using the refresh token", "Step 2 - Updating the security object", in the line:

'refresh_token ': 'YOUR_SAVED_REFRESH_TOKEN'

there is an extra space after token.  Made me have to actually look at what I was copy/pasting :)

**Comment by Kyria** [comment]
Fixed, thanks for reporting it :)
