### ISSUE TITLE
Change URLs for security object

### ISSUE THREAD

**Issue by Kyria** [Kyria/EsiPy#20]
The goal is not to depend on the app object anymore (the URLs shouldn't change anyway, but who knows).

This will also give the ability to create EsiSecurity object without having to get a swagger spec before. 

- [x] Change verify endpoint to use `https://esi.tech.ccp.is/verify` instead of `https://login.eveonline.com/oauth/verify`
- [x] Add the ability to override (in args) the other base URLs (`https://login.eveonline.com/`) 

Keep `app` for backward compatibility, but also for the ease of using URLs, especially if someone switch between servers (TQ/SISI) they'd not need to switch URL manually, but only the swagger spec datasource.

Priority for oauth/token and oauth/authorize url: 
- if nothing provided: TQ URL is default
- if one base URL or App is given, use it (<--- EsiPy won't check if base URL works, so may result in failures for user)
- if both (url, app), always use app (current behavior, preferred)

**Comment by Sophie-Hawley** [comment]
Also going to request the following step be added:

- [ ] Ensure that the EsiSecurity object is able to handle both web app and local app flows.

as EVEMon lead dev Ashita is working with CCP to allow for app credentials to be per user for local applications. Source: https://redd.it/77l1x0

**Comment by Kyria** [comment]
Can you explain a bit what you mean? Because as far as I understand that request, it's already the case, so i'm probably missing something ?

**Comment by Sophie-Hawley** [comment]
maybe i'm misunderstanding something, i'll double check

**Comment by Kyria** [comment]
Yes and no. I only want to remove the requirement to use it with EsiSecurity. 

What I want to do is : 
1. https://github.com/Kyria/EsiPy/blob/master/esipy/security.py#L56 change this line to use [ESI verify](https://esi.tech.ccp.is/verify/) instead of SSO verify (the most important change of this issue actually)
2. https://github.com/Kyria/EsiPy/blob/master/esipy/security.py#L64 change this to a default (tranquility) URL, unless an "app" object (like the current behavior) or a "base sso url" (login.eveonline.com) is provided, to be able to create security object before having to make an "app" 

The 2. is actually just a comfort change and won't change the current behavior, but just add some parameter to `EsiSecurity.__init__()`

**Comment by Sophie-Hawley** [comment]
Ahh, my bad then. For some reason I thought there was a much more significant rewrite about to happen and I wanted to make sure whoever did it didn’t code into a dead end
