### ISSUE TITLE
Error when setting -1 timeout with redis cache

### ISSUE THREAD

**Issue by tekkis** [Kyria/EsiPy#22]
So in the case that no caching of the call should take place while using redis (and possibly other cache types) the client code sets a -1 timeout which causes redis to puke with: 

invalid expire time in setex
--

I have a fix I just need to get it in a pull request for you to look at. I don't think it will break anything =).

**Comment by Kyria** [comment]
I know I took time to release that correction, i'm sorry. But at least, this is now out in version 0.3.0 !

Thanks for the report / PR :)

**Comment by tekkis** [comment]
Awesome, np, thanks for the update.
