### ISSUE TITLE
Cannot import name App

### ISSUE THREAD

**Issue by chriswellsfl1991** [Kyria/EsiPy#28]
Watch it this is a newbie mistake..

so I used pip to install esipy and its prerequisites, however, it required SUDO to actually install..whenever I try to run the examples provided, or in this example just trying to import it, it just will not work.  So here's the example:

```Python 2.7.9 (default, Sep 17 2016, 20:26:04)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import esipy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/esipy.py", line 1, in <module>
ImportError: cannot import name App

Python 2.7.9 (default, Sep 17 2016, 20:26:04)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from esipy import App
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/esipy.py", line 1, in <module>
ImportError: cannot import name App

Python 3.4.2 (default, Oct 19 2014, 13:31:11)
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import esipy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: bad magic number in 'esipy': b'\x03\xf3\r\n'
```

it says the same thing if in a file and ran, and never goes beyond the first line here. I'm not sure what I'm doing wrong..but here's the code from the website I'm trying to test with:

```from esipy import App

# App.create(url, strict=True)
# with url = the swagger spec URL, leave strict to default
app = App.create(url="https://esi.tech.ccp.is/latest/swagger.json?datasource=tranquility")
```

I'm guessing I did something fundamentally wrong, but, all the requirements are installed that are on the list..so..

**Comment by Kyria** [comment]
So, to summarize: 
- you installed esipy by doing `pip install esipy`
- you open a python shell with `python`
- you get this error ?

Questions: 
- Did you try using a virtualenv instead of installing system wide the lib ?
- do you have a file named "esipy" where you do the test

**Comment by chriswellsfl1991** [comment]
I'm working on a virtualenv, but straight installing it for the virtualenv didn't fix it.

I'm working on trying to make sure that the EsiPy install is "included." It's in the lib folder, I can access other things from the lib folder (both in and out of the virtualenv), but..so far, nothing. I have added thr esipy directory to the virtualenv (add2virtualenv), but so far It give the same issue.

Should I have placed the Python file I'm trying to run, in a specific location, to get it to work?

**Comment by Kyria** [comment]
If you install it using pip while a virtualenv is activated, it should install it at the right location and you should have nothing to do but just `pip install esipy`

Can you try the following (wherever you want, assuming you are on a *nix OS):
```shell
virtualenv env
source env/bin/activate
pip install esipy
python -c "import esipy"
```

if you use virtualenvwrapper, it's almost the same iirc
```shell
mkvirtualenv esipy_test_venv
workon esipy_test_venv
pip install esipy
python -c "import esipy"
``` 

Both shouldn't give you errors :/ 

Tbh, i don't really understand what you are trying to do while trying to add esipy...

**Comment by chriswellsfl1991** [comment]
I get:
```
pi@ChrisPi:~/www $ virtualenv env
New python executable in /home/pi/www/env/bin/python
Installing setuptools, pip, wheel...done.
pi@ChrisPi:~/www $ source env/bin/activate
(env) pi@ChrisPi:~/www $ pip install esipy
Collecting esipy
Collecting pytz (from esipy)
  Using cached pytz-2017.3-py2.py3-none-any.whl
Collecting pyswagger>=0.8.31 (from esipy)
Collecting six (from esipy)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting futures (from esipy)
  Using cached futures-3.2.0-py2-none-any.whl
Collecting requests (from esipy)
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting validate-email (from pyswagger>=0.8.31->esipy)
Collecting pyaml>=15.03.1 (from pyswagger>=0.8.31->esipy)
  Using cached pyaml-17.12.1-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->esipy)
  Using cached certifi-2018.1.18-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->esipy)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests->esipy)
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests->esipy)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting PyYAML (from pyaml>=15.03.1->pyswagger>=0.8.31->esipy)
Installing collected packages: pytz, validate-email, PyYAML, pyaml, six, pyswagger, futures, certifi, chardet, idna, urllib3, requests, esipy
Successfully installed PyYAML-3.12 certifi-2018.1.18 chardet-3.0.4 esipy-0.3.0 futures-3.2.0 idna-2.6 pyaml-17.12.1 pyswagger-0.8.37 pytz-2017.3 requests-2.18.4 six-1.11.0 urllib3-1.22 validate-email-1.3
(env) pi@ChrisPi:~/www $ python -c "import esipy"
(env) pi@ChrisPi:~/www $
```

well, I got a file to run and do its thing properly..sorry about that :/ thank you for the help.

one other thing I did was completely clean "pip" of the old packages. I'll reinstall what I need, but not sure if that did the trick or what.
