### ISSUE TITLE
ESI Posting / Editing bulk contacts

### ISSUE THREAD

**Issue by IPFR33LY** [Kyria/EsiPy#33]
Hello, I'm not sure if i'm doing this right or not but if I could get some help. I'd appreciate it.

below, the esiapp is configured to use /v1/ of esi.

```python
set_contacts = esiapp.op['post_characters_character_id_contacts'] \
    (character_id=current_user.character_id, contact_ids=x, standing=float(-10),)
```
the variable "x" is an array of 100 INT(character_ids) of other players.

When i use the above and when i check the url / path it's going to use, it seems to always be

```
/v1/characters/{character_id}/contacts/
```

and never replaces the {character_id}. do i have to do that manually? i always get a 500 error when the next line runes.

```
r = esiclient.request(set_contacts)
```

**Comment by Kyria** [comment]
If you want to check the URL, you need to do it after you do the request:

```python
from esipy import *
app = EsiApp()
client = EsiClient()
op = app.get__latest_swagger.op['get_markets_region_id_orders'](region_id=10000002)

op[0].url
# u'//esi.tech.ccp.is/v1/markets/{region_id}/orders/'

res = client.request(op)

op[0].url
# u'https://esi.tech.ccp.is/v1/markets/10000002/orders/'
```

You need to check the response body, CCP, even if they return 500, should return a valid json response, so you can get it with the `.raw` attribute at least, and probably `.data`.

So without error message, I can't really tell if the issue is your side, ccp's, mine or even in pyswagger. 

Also, do some contact from the list already exist ? Because POST is to add and PUT is to update for that endpoint, so it also may generate issues. To be verified.

**Comment by Kyria** [comment]
Actually, I just found your reddit thread https://www.reddit.com/r/evetech/comments/8du4id/bulk_editing_contacts_through_esi/ 

I tested with my char, but it seems to work with only one char... 

```python
# test 1
op = esiapp.op['post_characters_character_id_contacts'](character_id=961633431, standing=float(10), contact_ids=[95938980])
res = esiclient.request(op)

res.data
# [95938980]
res.status
#201

#test 2
op = esiapp.op['post_characters_character_id_contacts'](character_id=961633431, standing=float(10), contact_ids=[93903472])
res = esiclient.request(op)

res.data
# [93903472]
res.status
# 201
```

**Comment by IPFR33LY** [comment]
Hey. I just wanted to reply and tell you that I figured out my stupidity. I never checked my list for duplicates.

Duplicate entries breaks ESI with a 500 error. Here is what I added / have and it works. I'm sorry for wasting your time.


```python
    if len(contacts_list) > 100:
        popping_cucks = list(chunk(contacts_list, 100))
        for x in popping_cucks:
            x = list(set(x))
            x = sorted(x)
            set_contacts = esiapp.op['post_characters_character_id_contacts'](character_id=current_user.character_id, contact_ids=x, standing=float(-10),)
            r = esiclient.request(set_contacts)
```

**Comment by Kyria** [comment]
Good to know, thanks for sharing! :)
