### ISSUE TITLE
Add Etag to cache mechanism

### ISSUE THREAD

**Issue by ArchEcho** [Kyria/EsiPy#36]
Please refer to [this ccp post](https://developers.eveonline.com/blog/article/esi-etag-best-practices)

> # CACHING CONSIDERATIONS
> ### Things application developers will want to consider:
> 
> 1. Store ETag values with their response data independent of the cache timers (ie; do not expire your data just because the Expires time is in the past)
> 2. Request using the If-None-Match header with the last known ETag as its value
> 3. When you get a 304 response, continue using the last known data. You can use the updated Expires and Date headers to determine when the next possible update will be

**Comment by Kyria** [comment]
Yep, I will look at this to see how I can add ETags in EsiPy. 
Thanks for the reminder / issue :)

**Comment by Kyria** [comment]
released in 0.4.0, thanks !
