### ISSUE TITLE
Returning cached Responses for methods that should stale the resource

### ISSUE THREAD

**Issue by SpeedProg** [Kyria/EsiPy#39]
If you do a request 
**GET** /path/
it caches that response
if you do afterwards a
**PUT** /path/ or **POST** /path/ **DELETE** /PATH/
the request is never sent and instead you get a cached response back.

Solution:
Include the method in the cache key
or just not look at the cache for POST/PUT at all.
(through PUT/DELETE to an entity should actually expire the cached request)
[RFC2616](https://www.ietf.org/rfc/rfc2616.txt)
9.5 POST Contains:

> Responses to this method are not cacheable, unless the response
   includes appropriate Cache-Control or Expires header fields. However,
   the 303 (See Other) response can be used to direct the user agent to
   retrieve a cacheable resource.

9.6 PUT Contains:

> If the request passes through a cache and the Request-URI identifies
   one or more currently cached entities, those entries SHOULD be
   treated as stale. Responses to this method are not cacheable.

9.7 DELETE Contains:

> If the request passes through a cache and the Request-URI identifies
   one or more currently cached entities, those entries SHOULD be
   treated as stale. Responses to this method are not cacheable.

In case it is decided to never cache POST: the method would not be needed in the caching key BUT the cache should not be checked on PUT or POST or DELETE.
(Well on PUT/DELETE you should kinda of check it for a cached GET/POST and remove those)

In case you are wondering where we are hitting this on ESI: Fleet Endpoint :)

**Comment by Kyria** [comment]
So, as i've done it, to let you know: i've chosen not to cache any of the 3 (even 4, thx HEAD just in case) in any cases. 
But also i don't invalidate existing cache from any GET that may have been done before, because after asking on tweetfleet, making some test, it looks like ESI doesn't invalidate the cache on its side. 
So it would just result of querying once more the same stale data with outdated information.

I hope it's ok for you :) (it'll be in the next release, once i have finished everything i need to)

**Comment by SpeedProg** [comment]
It wasn't really a problem at all for me once I remembered to disable the cache (I fixed this in my patched version of your 0.8 client by not checking cache for post/put/delete).
And disabling the cache wasn't a problem since all my api info flows through caching anyway.
Just wanted to report this here since there might be other people with the same problem in the future :)

**Comment by Kyria** [comment]
released in 0.4.0, thanks !
