### ISSUE TITLE
EsiSecurity.verify fails with JSONDecodeError

### ISSUE THREAD

**Issue by SpeedProg** [Kyria/EsiPy#41]
EsiSecurity.verify fails with JSONDecodeError if the response it gets from the SSO is not json.
It would be good to actually get the raw response back in the APIException is this case and not have it fail with the JSONDecodeError.

**Comment by SpeedProg** [comment]
auth and refresh probably have the same thing happening

**Comment by Kyria** [comment]
For `auth`/`refresh`:
If SSO returns non valid json as 200 response, it's a bug their side.
If their error message is not json, well, i'm fine fixing it, but what are we supposed to get ?

For `verify`, since it's provided by ESI, it's the same issue of 520 with other endpoints. 
I'll take a look at it

**Comment by SpeedProg** [comment]
the other esi calls (done in the client) don't do the json_response=res.json() through which causes the exception. I'd just recommend you cache the exception and set the json_response to None or {} or idk so you can properly return you APIException.
Maybe add raw text to the exception (or the complete response).

Anyway It is hard to for me to figure out how to react in my code if I can't even the the the status code because the lib just throws that exception which doesn't not forward any information to me. (Apart from that I wouldn't expect that exception from the call)

Also you mean 504 probably? 520 are the monolith errors.

**Comment by Kyria** [comment]
504 yes :) i was mistaken (doing too much things at a time never help)

**Comment by Kyria** [comment]
Fixed it. 
It will be released in the next version later today / tomorrow :)

**Comment by Kyria** [comment]
released in 0.4.3
