### ISSUE TITLE
Add ability to revoke tokens

### ISSUE THREAD

**Issue by ArtificialQualia** [Kyria/EsiPy#44]
There doesn't appear to be a way to revoke tokens in this client.  The ability to revoke tokens is important for many applications that would use this.

It can of course be done manually, but implementing ESI stuff manually defeats the purpose of having this tool.

Would you consider adding that functionality into this library?  See here: http://eveonline-third-party-documentation.readthedocs.io/en/latest/sso/tokenrevocation.html

**Comment by Kyria** [comment]
This has been released in 0.5.0, thanks for the report :)
