### ISSUE TITLE
HTTP Error 400: invalid_request when setting EsiSecurity.auth()

### ISSUE THREAD

**Issue by porowns** [Kyria/EsiPy#45]
Recently, CCP started requiring State to be set for SSO to function. (I guess? See error below)

`{error":"invalid_request","error_description":"The state parameter is required."}`

To fix this, I added State="None" when retrieving my URI, 
`ESI_URL_CACHE = ESI_SECURITY.get_auth_uri(scopes=ESI_SCOPES, state=None)`

Note, ESI_SCOPES variable is set as:
```
ESI_SCOPES = [
    'publicData',
    'esi-contracts.read_character_contracts.v1',
    'esi-location.read_location.v1',
    'esi-location.read_ship_type.v1',
    'esi-mail.read_mail.v1',
    'esi-skills.read_skills.v1',
    'esi-skills.read_skillqueue.v1',
    'esi-wallet.read_character_wallet.v1',
    'esi-characters.read_contacts.v1',
    'esi-corporations.read_corporation_membership.v1',
    'esi-assets.read_assets.v1',
    'esi-fleets.read_fleet.v1',
    'esi-fleets.write_fleet.v1',
    'esi-characters.read_chat_channels.v1',
    'esi-industry.read_character_jobs.v1',
    'esi-markets.read_character_orders.v1',
    'esi-characters.read_corporation_roles.v1',
    'esi-location.read_online.v1'
]
```

Now, my SSO process receives an invalid_request error when setting the auth code for EsiSecurity.
```
File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "REDACTED", line 35, in receive_token
    esi_token = settings.ESI_SECURITY.auth(code)
  File "/usr/local/lib/python3.5/dist-packages/esipy/security.py", line 292, in auth
    response_header=res.headers
esipy.exceptions.APIException: HTTP Error 400: invalid_request
```

Do you have any ideas on what the underlying issue may be here? My SSO functionality has been stable for a very long time, did I miss an update?

**Comment by Kyria** [comment]
>To fix this, I added State="None" when retrieving my URI,

This shouldn't change anything, if state is None/empty [it doesn't add it to the URL](https://github.com/Kyria/EsiPy/blob/master/esipy/security.py#L196)

My guess is that it's not an error from your side: i just tested exactly the same (using your scopes, how you generate your URL etc), and it's working fine...
So either try to regenerate your app clientID/secret (keep in mind that will probably invalidate all refresh your may store), or probably just ask on tweetfleet slack channel #sso, it was maybe a temporary issue. 

On a side note, even if state is not mandatory, you'd better use it for security reason :)

**Comment by porowns** [comment]
Per our conversation, this was resolved by removing `app=ESI_APP` from ESI_SECURITY.
```
ESI_SECURITY = EsiSecurity(
    --> REMOVE app=ESI_APP,
    redirect_uri=ESI_CALLBACK_URL,
    client_id=ESI_CLIENT_ID,
    secret_key=ESI_SECRET_KEY,
    headers={'User-Agent': 'X'}
)
```
