### ISSUE TITLE
oauth v2 is now live, EsiPy is trying to use a mix of v2 and v1 by default

### ISSUE THREAD

**Issue by ArtificialQualia** [Kyria/EsiPy#46]
When you have EsiPy generate your auth url (via `esisecurity.get_auth_uri`) you get directed to the v2 endpoint.  This gets you a JWT that, when used with `esisecurity.verify()`, gives you this error: 
`HTTP Error 400: b'{"error":"invalid_request","error_description":"Invalid authorization code, decrypt failed"}'`

To prevent this issue in the future, maybe you could use this endpoint: `https://login.eveonline.com/.well-known/oauth-authorization-server` to get the latest oauth endpoints automatically rather than using a mix of "securityDefinitions" from swager.json and hardcoding them.

**Comment by Kyria** [comment]
Just saw that after some discussion (see #45 )

I'll have a look to change everything to be "right and working" :) 

Currently (in case, for people having trouble): 
- don't add the  `app` parameter to EsiSecurity
- change the `sso_url` parameter to be "https://login.eveonline.com/v2" (didn't test, can / should work)

**Comment by ArtificialQualia** [comment]
Yeah, I changed `'%s://%s/oauth/token'` to `'%s://%s/v2/oauth/token'` and '%s://%s/oauth/revoke' to '%s://%s/v2/oauth/revoke' in lines 84 and 88 respectively in security.py and it's working for me now, and that's with providing the `app` parameter, and it is working for me, so that is an option for those who don't want to remove their app parameter.

**Comment by Kyria** [comment]
Released in v1.0.0, please have a look at the release note and the docs :) 

Thanks for the report
