### ISSUE TITLE
SSO example - api_info missing dict entry

### ISSUE THREAD

**Issue by avenhor** [Kyria/EsiPy#50]
Using the SSO example from the documentation, the section in Step 5 is broken:
```
api_info = security.verify()

# now get the wallet data
op = app.op['get_characters_character_id_wallet'](
    character_id=api_info['CharacterID']
)
```
`CharacterID` is not returned in the dictionary, so it has to be manually added by
`api_info['CharacterID'] = api_info['sub'].split(':')[-1]`

**Comment by Kyria** [comment]
Thanks for reporting it, i've fixed the example :)
