### ISSUE TITLE
[Question] What does ETag do exactly?

### ISSUE THREAD

**Issue by y0rn** [Kyria/EsiPy#53]
Hi,
I know ETag has been implemented in EsiPy but do we have a way to know if the data we get is coming from cache? Or even better, **how can I get a 304 error instead of the cached result**?
Thank you very much, sorry if my question is dumb...

**Comment by Kyria** [comment]
currently, you can't really know if it has come from a cached result or not and you can't get a 304 "error" (and it's not an error actually). 
I can't also change the return code from 200 to 304, as it might break existing use that check if status = 200.

The "only" solution for now is to store the etag from previous calls, and compare to the response you get.

May I ask what you want to do with that information ?

**Comment by y0rn** [comment]
Thank you very much for your answer. I understand that we can't know if the result is cached or not, but as you said, if I save each etag and check it in a response, I could avoid computing the result.

Now please tell me, is a HEAD request made before each GET request to check that etag in EsiPy? If so, do I need to do anything when initializing the EsiApp?

To make it simple, I need my script to be as resource saving as possible by avoiding to download (and even less compute) results I have already downloaded. So far what I've done is savinf all etags and making a HEAD request before any GET, but for hundreds of pages, it's ultimately slower...

**Comment by Kyria** [comment]
> Now please tell me, is a HEAD request made before each GET request to check that etag in EsiPy? If so, do I need to do anything when initializing the EsiApp?

No its not doing a head request, because it's not useful: when you perform a request using etag, the standard behavior if the data didn't change is to return a empty body http 304 response (as explained [here](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.3.5), telling you to reuse your cache. So basically, you have no more data than a head request, but you did a GET.

Example with the forge region (page 1 only) (that's basically what happens in EsiPy) :
```python
>>> URL='https://esi.evetech.net/v1/markets/10000002/orders/' 
>>> r1 = requests.get(URL) 
>>> r1.status_code 
200
>>> len(r1.content)
238216
>>> r2 = requests.get(URL, headers={'If-None-Match': r1.headers['etag']})
>>> r2.status_code 
304
>>> len(r2.content)
0 
```

As you can see, the second request, which is using etag have no content. That's why I just return the cache, with updated "date" and "expiry" header from esipy when I get a 304. 

So for your script, you can just use EsiClient.request() with a persistent cache, and you know it will only download the data when expired AND etag changed due to how HTTP 304 works

**Comment by y0rn** [comment]
Ok I understand, so with 

`EsiApp(cache_time=None)`

will 

> it will only download the data when expired AND etag changed due to how HTTP 304 works

still be true?

Thank you for taking time to answer me, it's much appreciated

**Comment by Kyria** [comment]
I'd like to say yes, because it was what i intended to do in the beginning, but i'd say, i'd need to check and test it again. (in case of doubt, just set a cache_time big enough to fit your need, as it's only for the swagger.json file themselves here, so they don't change often)

**Comment by y0rn** [comment]
Ok I thought it was a general rule for the client, nervermind.

The code example you gave me using `requests` helped me write what I needed to get that 304 status code I wanted so much, since I was already saving all etags. I _believe_ it's better (regarding computing time) than "unwrapping" data from cache and not processing it in my code.

Maybe it would have been a nice option in the library, because it does such a great job managing the tokens that even now, I still need it for endpoints that need authentication.

**Comment by Kyria** [comment]
this may not be a bad idea, but I need to see how to add this without too much overheads (also adding the ability to the security to just add/get the sso headers, already updated)

**Comment by y0rn** [comment]
Thanks for considering it, I must say that performances are much better with that 304 code.

Regarding the headers, I had to refresh the token at start to access it, then make my request myself including it, then catching the 401, refreshing it again then retrying the request.
