### ISSUE TITLE
Market orders not caching with FileCache

### ISSUE THREAD

**Issue by jtrenaud1s** [Kyria/EsiPy#54]
When I download market orders using esipy, and rerun the program, it has to redownload all the market orders instead of pulling them from the cache. I checked the cache.db and the files, a lot of the folders are empty, and in the db file, a good number of the rows don't have data, and I'm assuming these are market order rows. Is this intended for information accuracy? Is the cache simply expiring very quickly for market orders?

**Comment by Kyria** [comment]
Market orders have like 5min cache time from ESI if I remember correctly. So if you pull them outside this range, you'll likely hit expired cache and download again. 

Other than that, i've only checked that the FileCache is working as intended (caching files) but never tried it with specific endpoints / checking the files behind to see how it's storing files. 

If you are testing to get market within the 5min range and have this issue, would you mind sharing your code so I can test it also on my side ?

**Comment by jtrenaud1s** [comment]
This makes some sense, considering I was pulling orders for over 2000 items at a time, on one thread, which would take a good few minutes. Since I started using the multi_request method download times have been reduced to mere seconds so this shouldn't really be much of an issue anymore.
