### ISSUE TITLE
Update swagger root URL in documentation

### ISSUE THREAD

**Issue by void4** [Kyria/EsiPy#56]
The URL on this page: https://kyria.github.io/EsiPy/getting_started/basic_usage/

Needs to be changed from `https://esi.tech.ccp.is/latest/swagger.json?datasource=tranquility`
to
`https://esi.evetech.net/latest/swagger.json?datasource=tranquility` since the former raises a 404 error

**Comment by Kyria** [comment]
I've updated it. Though I had fixed all these already, but looks like i've forgotten that one.

Thanks!
