### ISSUE TITLE
Esipy redis cache cleanup

### ISSUE THREAD

**Issue by s4mur4i** [Kyria/EsiPy#57]
When using esipy with redis cache a lot of objects are left back. 
Is there a recommended way to clean up old cache objects, or is it safe to delete everything older then x time (like a day)?

Thank you

**Comment by Kyria** [comment]
I was going to say it's supposed to be done automatically, but it's only true if you query a key that already exists... Now I can't remember why I removed the timeout value from the cache itself and only moved it inside the request thing...

Until then, it's really up to you: you can daily flush your redis cache or even more frequently (really depends on the endpoints you are querying) 

i'll try to have a look at this to fix this. 
Thanks :)
