### ISSUE TITLE
Wondering if the client can handle existing auth and refresh tokens

### ISSUE THREAD

**Issue by Regner** [Kyria/EsiPy#6]
I have the getting and saving of the access and refresh tokens already and in a way I don't really want to change.

I was wondering if it was possible to supply the access token and refresh token myself when initializing the client. I was also hoping it was also possible to supply a callback of some kind for when the access token gets refreshed so I could persist it to my DB.

**Comment by Kyria** [comment]
With what currently exists, you only can manually update the tokens in the security object using the `EsiSecurity.update_token()` method.

As you manage the tokens yourself (and you don't want esipy to actually do something else than just updating the headers I believe), a simple solution I can see would be:
1. Create your security object
2. Create your client, giving him the security
3. Manually updating the client with (only) `access_token` and the `expires_in` value 

This way, you can use it normally, update it when necessary (and if you don't, it will throw an [AttributeError Exception](https://github.com/Kyria/EsiPy/blob/master/esipy/security.py#L161-L162) as the security object cannot update the token without refresh token)

For the callback, you can do it with the [signals](http://esipy.readthedocs.io/en/latest/advance/signals/). In your app just do something like this: 
```python
def callback_update_token(access_token, refresh_token, expires_in):
   # whatever you need it there

from esipy.event import after_token_refresh
after_token_refresh.add_receiver(callback_update_token)
```

Then, each time the token is automatically refreshed (when doing a `EsiClient.request()`), your `callback_update_token` function will be triggered. (I didn't set it for manual update, as i don't believe you need a callback when you manually update tokens).

**Comment by Regner** [comment]
I can rebuild the token JSON object as I have all of that data. So it seems I should be able to build a security object normally, but instead of using `EsiSecurity.auth()` I use `EsiSecurity.update_token()` and then pass the security object into the client I should be OK.

So if I used the security object in that way I could just hook into that signal to save the new tokens when needed.

Do I understand that right?

**Comment by Kyria** [comment]
Yes that's it :)

**Comment by Regner** [comment]
Awesome! Thanks for the information. :)
