### ISSUE TITLE
Not possible to use EsiSecurity.verify with only a access_token

### ISSUE THREAD

**Issue by cbz** [Kyria/EsiPy#67]
In line with the section " Use the access token to get the character ID" in https://developers.eveonline.com/blog/article/sso-to-authenticated-calls it should be possible to get character information using just the access_key against the verify URL.

I've tested this using curl and an access key I generated and found it to be the case.  However, the current behaviour of the verify method on EsiSecurity is to as far as I can tell - to use the previous information generated during a full oauth flow.  Short of doing the request outside ESi there's no current method that I can see that would allow one to get the character info from just the access token.

**Comment by Kyria** [comment]
I don't get your issue actually... you just have to use the `EsiSecurity.update_token` method to update the access_token in your security object, then use `.verify()` which don't even use the endpoint but decode the JWT access token ?
You should have your user ID in the "sub" value of the token. 

Otherwise you'll need to be more precise / provide example i'm afraid...

**Comment by Kyria** [comment]
Also, as far as I know, https://login.eveonline.com/oauth/verify is supposed to be deprecated for v2 tokens (jwt) and you need to use https://esi.evetech.net/ui/?version=meta#/Meta/get_verify (which means you need to make a request to this endpoint, providing the token).

**Comment by cbz** [comment]
> I don't get your issue actually... you just have to use the `EsiSecurity.update_token` method to update the access_token in your security object, then use `.verify()` which don't even use the endpoint but decode the JWT access token ? You should have your user ID in the "sub" value of the token.
> 
> Otherwise you'll need to be more precise / provide example i'm afraid...

Okay, the following code takes an access token created at another step and attempts update_token and then verify:

```
# -----------------------------------------------------------------------
# ESIPY Init
# -----------------------------------------------------------------------
cache = RedisCache(redis.Redis(host='localhost', port=6379, db=1))

# create the app
esiapp = EsiApp().get_latest_swagger

# init the security object
esisecurity = EsiSecurity(
    redirect_uri=config.ESI_CALLBACK,
    client_id=config.ESI_CLIENT_ID,
    secret_key=config.ESI_SECRET_KEY,
    headers={'User-Agent': config.ESI_USER_AGENT}
)
esisecurity.update_token({'access_token': ESI_USER_TOKEN, 'expires_in': 1199})

# init the client for auth endpoints
esiauthclient = EsiClient(
    security=esisecurity,
    headers={'User-Agent': config.ESI_USER_AGENT},
    cache = cache
)
# init the client for normal endpoints
esiclient = EsiClient(
    headers={'User-Agent': config.ESI_USER_AGENT}
)

print(f'{esisecurity.verify()}')

```

It throws this error:

```
Traceback (most recent call last):
  File "/tmp/python/lib/python3.8/site-packages/jose/jws.py", line 176, in _load
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/python/lib/python3.8/site-packages/jose/jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
  File "/tmp/python/lib/python3.8/site-packages/jose/jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
  File "/tmp/python/lib/python3.8/site-packages/jose/jws.py", line 180, in _load
    raise JWSError("Not enough segments")
jose.exceptions.JWSError: Not enough segments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "check_hall.py", line 69, in <module>
    print(f'{esisecurity.verify()}')
  File "/tmp/python/lib/python3.8/site-packages/esipy/security.py", line 411, in verify
    return jwt.decode(
  File "/tmp/python/lib/python3.8/site-packages/jose/jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
```

**Comment by Kyria** [comment]
i'm not able to replicate using a v2 token, but if I put a shitty value (not respecting the JWT format) i get the same issue.

So a few questions: 
- is your access token a JWT token (you can check it by checking the format, it should be `XXXX.YYYY.ZZZZ`), you can also put it in https://jwt.io and it should provide real values
- against what SSO endpoint did you create the token (/v2/... or not, like the above outdated documentation?) ?
- you can find all valid endpoints here for the SSO part: https://login.eveonline.com/.well-known/oauth-authorization-server

EsiPy uses the /v2 SSO, so you can't use a legacy token with it (you need to refresh it if you have a refresh token, or generate a new one against the right endpoints)
Docs are here: https://docs.esi.evetech.net/docs/sso/ and https://docs.esi.evetech.net/docs/sso/web_based_sso_flow.html

**Comment by Kyria** [comment]
any update @cbz ?

**Comment by cbz** [comment]
Hi thanks for that - I think you are right, while I can't get a XXXX.YYYY.ZZZZ style token, by explicitly specifying the auth endpoint to https://login.eveonline.com/v2/oauth/token I can get something from which I can call your method - is there any reason it returns a different format to that returned by [https://esi.evetech.net/ui/?version=meta#/Meta/get_verif](https://esi.evetech.net/ui/?version=meta#/Meta/get_verify) btw?

**Comment by Kyria** [comment]
"my" verify methods just parse (base64 decode + check validity) the token, so it returns everything in the default values from jwt. 
the /verify endpoint returns things in the eve online format. 

I'll close as it's seems it's solved. :)
