### ISSUE TITLE
client.request bug

### ISSUE THREAD

**Issue by centric-jim** [Kyria/EsiPy#8]
Exploring EsiPy I think I may have found a bug that appends an additional **https:** to the request url every time you call it.  The first time you make a call it runs correctly. For each additional iteration of that call an **https:** is appended

Let me try and give a reproducible example:

```
from esipy import App, EsiClient
app = App.create('https://esi.tech.ccp.is/latest/swagger.json')
client = EsiClient()

  /# market order endpoints (jita, all order type, tritanium)
market_order_operation = app.op['get_markets_region_id_orders'](
    region_id=10000002,
    type_id=34,
    order_type='all',
)

item_order = client.request(market_order_operation)
item_order.status

```
Out[8]: 200

So that's good
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Now just call it directly again and note the end URL and the dual **https:https:**
'**https:https**://esi.tech.ccp.is/latest/markets/10000002/orders/?type_id=34&order_type=all&page=1&datasource=tranquility'

```client.request(market_order_operation)```

---------------------------------------------------------------------------
InvalidSchema                             Traceback (most recent call last)
<ipython-input-13-84bd2de1398c> in <module>()
----> 1 client.request(market_order_operation)

/usr/local/lib/python2.7/dist-packages/EsiPy-0.1.2-py2.7.egg/esipy/client.pyc in request(self, req_and_resp, raw_body_only, opt)
    128             res = self._session.send(
    129                 prepared_request,
--> 130                 stream=True
    131             )
    132 

/usr/lib/python2.7/dist-packages/requests/sessions.pyc in send(self, request, **kwargs)
    551 
    552         # Get the appropriate adapter to use
--> 553         adapter = self.get_adapter(url=request.url)
    554 
    555         # Start time (approximately) of the request

/usr/lib/python2.7/dist-packages/requests/sessions.pyc in get_adapter(self, url)
    596 
    597         # Nothing matches :-/
--> 598         raise InvalidSchema("No connection adapters were found for '%s'" % url)
    599 
    600     def close(self):

InvalidSchema: No connection adapters were found for '**https:https**://esi.tech.ccp.is/latest/markets/10000002/orders/?type_id=34&order_type=all&page=1&datasource=tranquility'

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Now call that a 3rd time -- note the end URL of 
'**https:https:https**://esi.tech.ccp.is/latest/markets/10000002/orders/?type_id=34&order_type=all&page=1&datasource=tranquility'

```
client.request(market_order_operation)
```
---------------------------------------------------------------------------
InvalidSchema                             Traceback (most recent call last)
<ipython-input-14-84bd2de1398c> in <module>()
----> 1 client.request(market_order_operation)

/usr/local/lib/python2.7/dist-packages/EsiPy-0.1.2-py2.7.egg/esipy/client.pyc in request(self, req_and_resp, raw_body_only, opt)
    128             res = self._session.send(
    129                 prepared_request,
--> 130                 stream=True
    131             )
    132 

/usr/lib/python2.7/dist-packages/requests/sessions.pyc in send(self, request, **kwargs)
    551 
    552         # Get the appropriate adapter to use
--> 553         adapter = self.get_adapter(url=request.url)
    554 
    555         # Start time (approximately) of the request

/usr/lib/python2.7/dist-packages/requests/sessions.pyc in get_adapter(self, url)
    596 
    597         # Nothing matches :-/
--> 598         raise InvalidSchema("No connection adapters were found for '%s'" % url)
    599 
    600     def close(self):

InvalidSchema: No connection adapters were found for '**https:https:https**://esi.tech.ccp.is/latest/markets/10000002/orders/?type_id=34&order_type=all&page=1&datasource=tranquility'

**Comment by jonobrien** [comment]
https://github.com/Kyria/EsiPy/blob/master/esipy/client.py#L67
duplicate mount calls?

**Comment by Kyria** [comment]
Yes actually I already saw that, but, as mentioned in the pyswagger bug you opened, it's currently "by design". 

The "best" current solution would be something like : 
```python

from esipy import App, EsiClient
app = App.create('https://esi.tech.ccp.is/latest/swagger.json')
client = EsiClient()

  /# market order endpoints (jita, all order type, tritanium)
market_order_operation = app.op['get_markets_region_id_orders']

item_order = client.request(market_order_operation(
    region_id=10000002,
    type_id=34,
    order_type='all',
))
item_order.status

# do something and call it again
item_order = client.request(market_order_operation(
    region_id=10000002,
    type_id=34,
    order_type='all',
))
```

I'll wait until the `prepared` flag for request is done in pyswagger before doing anything in EsiPy.

**Comment by centric-jim** [comment]
Please accept my apology for not posting a response here, that it was a pyswagger issue, when I posted on the pyswagger.

I also want to thank you for your work on this project.  I plan on making a pull request and adding more examples and maybe document this issue if that's ok with you?

Thanks again

**Comment by Kyria** [comment]
@centric-jim FYI I added in EsiPy 0.1.3 the same behavior pyswagger added in its latest release to be able to reuse an existing operation, so you shouldn't have anymore issue with the code you gave in the first post. 
Thanks for reporting it here and in pyswagger :)
